name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        env:
          TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        uses: docker/login-action@v3
        with:
          username: $USERNAME
          password: $TOKEN
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: yarnethatsme/rocketchat-push-gateway:latest
